### ISSUE TITLE
App identified as Intel instead of Universal on an Apple silicon machine

### ISSUE THREAD

**Issue by macOS-Mavericks** [dtseto/Hermes-master#1]
I just downloaded 1.3.2d1, but after unpacking it, it indicated it was for Intel after doing a Get Info, versus a Universal build. I haven't tested it since I have nothing on my M1 system that uses Rosetta 2.

**Comment by dtseto** [comment]
try it again rebuilt this morning with active architecture only off and it is slightly larger

**Comment by macOS-Mavericks** [comment]
<img width="494" alt="Screen Shot 2024-10-31 at 8 54 27 AM" src="https://github.com/user-attachments/assets/153fe5dc-740e-4d7b-9c52-50ec9346c874">

So on Monterey 12.6.3, this build works (via right-click open), but the UI is screwed up, please see the attachments. Knowing to type in my login blindly and then hitting the tab to the password field, I was able to get Hermes working on a silicon M1 ARM64 Mac.

<img width="474" alt="Screenshot 2024-10-31 at 9 51 52 AM" src="https://github.com/user-attachments/assets/8fc6a608-377f-44db-a8b8-0d0c4e741fa6">

The other UI problem is within Settings where Network won't fit into the window.

The last challenge is that the Hermes version 1.3.2d1 (2059) opens on top of other windows in Monterey (correctly), but does not on Sonoma 14.6.1 (Apple silicon). I have to close a mess of windows and find Hermes behind everything else.

**Comment by dtseto** [comment]
For the first one you can turn off the toolbar buttons in the menu to see it. 

For the second you should be able to drag the window to see the toolbar. 

I will try to fix these but the first one will take some time because they changed the window handling in the four years since the past version. As far as I know this is the only fork that has been built to arm.
